name: Build Linux

on:
  push:
    branches:
      - cpp
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Update apt get"
        run: sudo apt-get update && sudo apt-get upgrade -y

      - name: "Install required packages."
        run: sudo apt-get install -y build-essential ccache llvm-dev libclang-dev clang cppcheck libboost-all-dev curl libcurl4-openssl-dev doxygen git graphviz libssl-dev make ninja-build libomp-dev python3 python3-pip tar unzip wget iwyu

      - name: "Build"
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -GNinja .. && ninja

      - name: "Create python package"
        run: cd ${{ github.workspace }} && sh ./create_python_package